### ISSUE TITLE
local validation seems valid but is invalid according to editor.swagger.io

### ISSUE THREAD

**Issue by M4tini** [MyParcelCOM/api-specification#9]
commit: `5857b9b8d412bccfa43669f45d5b52787f9f8e44`
reproduce: `docker-compose run --rm validator curl -X POST -d @swagger.json -H 'Content-Type:application/json' http://localhost:8080/debug`
got: `{}`
expected: `Schema properties specified as 'required' must be defined`
test: paste `dist/swagger.json` content into [http://editor.swagger.io](http://editor.swagger.io)

**Comment by M4tini** [comment]
Similar issue with required path parameters which are not present. Local validation is successful but the actual build process runs into errors like this
`#/paths/~1shipments~1{shipment_id}~1statuses/get: API requires path parameter but it is not defined: shipment_id`

**Comment by SAMDevelopment** [comment]
Not something we will fix. We might move to another validator when switching to OpenApi 3.0.
